/**
 * Checks if HTML content is truly empty (strips tags and checks for images)
 * This handles empty paragraphs like <p><br></p> generated by rich text editors.
 */
export function isContentEmpty(html: string | null | undefined): boolean {
  if (!html) return true;

  // 1. Remove all HTML tags
  const textOnly = html.replace(/<[^>]*>/g, '').trim();

  // 2. Check for images (as they are meaningful content)
  const hasImages = /<img[^>]+>/.test(html);

  // 3. If there's no text and no images, it's effectively empty
  return textOnly.length === 0 && !hasImages;
}
