/**
 * Checks if HTML content is truly empty (strips tags and checks for images)
 * This handles empty paragraphs like <p><br></p> generated by rich text editors.
 */
export function isContentEmpty(html: string | null | undefined): boolean {
  if (!html) return true;

  // 1. Remove all HTML tags
  const textOnly = html.replace(/<[^>]*>/g, '').trim();

  // 2. Check for images (as they are meaningful content)
  const hasImages = /<img[^>]+>/.test(html);

  // 3. If there's no text and no images, it's effectively empty
  return textOnly.length === 0 && !hasImages;
}

/**
 * Strips all HTML tags and returns plain text.
 * Useful for summaries and cards.
 */
export function stripHtml(html: string | null | undefined): string {
  if (!html) return '';
  return html.replace(/<[^>]*>/g, '').replace(/&nbsp;/g, ' ').trim();
}
